### ISSUE TITLE
Turning site off causes php errors

### ISSUE THREAD

**Issue by influxweb** [ryanhowdy/fcms#488]
Hi Ryan,

I had used a previous version a couple years ago, I love the updates you've made with this script. I am seeing some odd errors. I installed the scripts, but receive ```PHP Error Undefined offset: 1``` once I log in. That error persists throughout all pages. If I try to make an edit in the administration portal, I still see that error but then I get ```PHP Error Cannot modify header information - headers already sent by (output started at /home2/hallowed/public_html/cafedraco/fcms.php:340)```.

Any pointers would be appreciated.

Cheers,
Matt

**Comment by saigosan** [comment]
Unsubscribe me please

**Comment by ryanhowdy** [comment]
Does the 'Undefine offset: 1' error give a file and line number?

**Comment by influxweb** [comment]
Hi Ryan,

Unfortunately, no. If I turn on debugging, this is the full listing.

PHP Error

Undefined offset: 1

PHP Error

Cannot modify header information - headers already sent by (output started at /home2/hallowed/public_html/cafedraco/fcms.php:340)

File: /home2/hallowed/public_html/cafedraco/admin/config.php

Line: 571

Stack:
#0 __construct called at [/home2/hallowed/public_html/cafedraco/admin/config.php:23]
#1 control called at [/home2/hallowed/public_html/cafedraco/admin/config.php:55]
#2 displayGeneralFormSubmit called at [/home2/hallowed/public_html/cafedraco/admin/config.php:80]
#3 header called at [/home2/hallowed/public_html/cafedraco/admin/config.php:571]
#4 fcmsErrorHandler called at [???:???]

PHP: 5.3.27 (Linux)

**Comment by influxweb** [comment]
Hi Ryan,

Okay, so I have figured something out. I had the setting for "Turn Off Site" set to Yes. If I switch that to no, all the errors go away.

**Comment by ryanhowdy** [comment]
Awesome.  Sounds like a real bug then.

Thanks for reporting it.

I've assigned this to the next release.

**Comment by influxweb** [comment]
Fantastic Ryan. Keep up the good work.
