### ISSUE TITLE
Photos are flipped upsidedown

### ISSUE THREAD

**Issue by ganastor** [ryanhowdy/fcms#503]
Final destination photos and thumbnails look fine (from uploads/photos/memberx, but in the gallery the cover and thumbnails are flipped upside down?

**Comment by ryanhowdy** [comment]
That's a new one.

What are you using to upload them?  Are they from your computer or instagram or something?

**Comment by ganastor** [comment]
Just my computer... jpeg images. I couldn't find anything in the code causing it either or I wouldn't have left such a vague remark, can't figure it out.

**Comment by ryanhowdy** [comment]
This probably has something to do with the photo EXIF orientation.

Which photos are incorrect?

There could be 3 different photos for each.
1. thumbnail
2. medium
3. full size (optional)

You mentioned thumbnail both being correct and incorrect, and also what do you mean by cover and final destination photos?

**Comment by ganastor** [comment]
I'm so sorry I thought I had let you know and guess I forgot... it is an EXIF issue.

By final destination I meant the link that actually holds the image was correct (View Image right click..) but the thumbnails in the Album as well as individual picture were wrong.

For brevity's sake I just converted them to lossless formats instead of fixing the EXIF, so they worked now.

Since I already see EXIF as an issue, I had also meant to close this.. so doing that now. Thanks for replying!
