### ISSUE TITLE
PHP Error after Install on ipage

### ISSUE THREAD

**Issue by bcnubes** [ryanhowdy/fcms#520]
Installed on ipage and got the "Hooray!" message that everything worked. There were no error messages during the 5 step install process. When I continued to the login page I got the following errors.

> PHP Error
> 
> Unknown: open(/var/php_sessions/sess_498c8ea9849b993faf7f235c3b7d12ef, O_RDWR) failed: No such file or directory (2)
> 
> PHP Error
> 
> Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/php_sessions)

The very similar error messages as written by ipage's log:

> 2016-01-30 18:49:39 - ERROR --> Unknown: open(/var/php_sessions/sess_498c8ea9849b993faf7f235c3b7d12ef, O_RDWR) failed: No such file or directory (2)
>   FILE  - Unknown [0]
>   PHP   - 5.5.22 (Linux)
>   STACK
>     #0 fcmsErrorHandler called at [???:???]
> 
>  
> 2016-01-30 18:49:39 - ERROR --> Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/php_sessions)
>   FILE  - Unknown [0]
>   PHP   - 5.5.22 (Linux)
>   STACK
>     #0 fcmsErrorHandler called at [???:???]

I confirmed that the User, Group and Other have full read, write and execute permissions on inc, and the upload folders. 

I can't login unless I have the remember me checkbox selected. If it isn't checked I get the Access Denied warning. If it is selected I can log in but the page is filled with php errors- date time errors repeated more than 100 times.

> PHP Error
> strtotime(): It is not safe...
> 
> PHP Error
> strtotime(): It is not safe

The admin page has different error messages.

> PHP Error
> 
> date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.
> 
> PHP Error
> 
> file(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0
> 
> PHP Error
> 
> file(http://www.familycms.com/latest/version.php): failed to open stream: no suitable wrapper could be found

I can navigate within the site, frontend or admin, but I can't make any changes, I always get some type of error message. 

Ipage Information
MySQL Version 	5.5.44
PHP Version 	5.5

**Comment by ryanhowdy** [comment]
Sounds like the php session configuration is not quite right.

Checking the 'remember me' option works because it uses cookies and not a php session.

**Comment by ryanhowdy** [comment]
The rest of the errors are because the timezone isn't being set in your php configuration.

See [this knowledge base article](http://support.familycms.com/kb/general/it-is-not-safe-to-rely-on-the-systems-timezone-settings) for more info.

**Comment by bcnubes** [comment]
Thank you Ryan, much appreciated. I don't know PHP but I will Google around a bit and see if I can figure something out regarding the sessions. Since it is a brand new install I can't break my site, well I can, but I won't lose anything. I will let you know if I figure anything out. Thanks again.


---- On Sat, 30 Jan 2016 13:39:36 -0800 Ryan Haudenschilt&lt;notifications@github.com&gt; wrote ---- 

Sounds like the php session configuration is not quite right.
 Checking the 'remember me' option works because it uses cookies and not a php session.
