### ISSUE TITLE
Birthday entries in calendar show actual user age instead 'is gonna be' age (age + 1)

### ISSUE THREAD

**Issue by fermino** [ryanhowdy/fcms#521]
This happens, and I'm already 16 D:

![bug-birthdays](https://cloud.githubusercontent.com/assets/8203176/13098135/2ea1a270-d506-11e5-9e30-04cfc65c3195.PNG)

Tested and verified, I'm searching for the code to make a PR with the fix. 

Regards!
-fermino-

BTW, congrats! FCMS is ~~almost~~ the **best** CMS ever xD

**Comment by fermino** [comment]
PR fix: #522.

**Comment by ryanhowdy** [comment]
Duplicate #393
