### ISSUE TITLE
still in development

### ISSUE THREAD

**Issue by petrk94** [ryanhowdy/fcms#546]
Hello
I would like to knwo whether fcms is still in active development?

**Comment by ryanhowdy** [comment]
Yes, although I don't spend as much time on it as I would like.

**Comment by petrk94** [comment]
Thats nice to hear, is there something what you need for help?
Im not a good coder, unfortunately only HTML and some css

**Comment by ryanhowdy** [comment]
I'm currently working on moving all the html out of the php code and into templates. #409

**Comment by petrk94** [comment]
Alright, sorry that I cant help. Good luck I stay tuned :)
