### ISSUE TITLE
Install - Error during installation process

### ISSUE THREAD

**Issue by Skyturtle** [ryanhowdy/fcms#558]
I tried an installation of fcms-3.7.0 in XAMPP of version 7.2.1 / PHP 7.2.1 (Windows 32-bit). While the installation process the following error is occurred: "Fatal error: Cannot redeclare ImageCreateFromBMP() in \path_to\fcms-3.7.0\familyconnections\inc\utils.php on line 3647".

**Comment by ryanhowdy** [comment]
This is a duplicate of #565 .
