### ISSUE TITLE
Bug or feature?

### ISSUE THREAD

**Issue by GregLeonhardt** [ryanhowdy/fcms#561]
In Configuration => Photo Gallery I changed the default from (Off 2 photos) to (On 3 photos) and when I look into the photos directory I can see that the full size images are in fact stored there.  However, everything being displayed on the site is still cropped (square).  What do I change to have the full (original uncropped) image displayed on the site.  As a sort of followup, is there or could there be a method to download full size images?

**Comment by ryanhowdy** [comment]
The only way you can see the full sized photo, is to click on the photo itself, then it will pop up and show you the original if you have it set to (On 3 photos).
