### ISSUE TITLE
(3.7.0) ERROR --> Invalid user id. - 0 | (3.6.2) ERROR --> PDO::__construct(): send of 5 

### ISSUE THREAD

**Issue by GregLeonhardt** [ryanhowdy/fcms#576]
After upgrading from  (Family Connections 3.6.2 )  to  (Family Connections 3.7.0 ) all attempts to create a post result in the following error.  [See the attached log message.]

I reported this problem some time ago.  After reverting back to 3.6.2 the issue seamed to go away and I never followed through with getting log records etc.  Anyhow another issue with 3.6.2 has come to light where photo uploads are failing.  [See second attached log message.]  This feature worked fine until I installed 3.7.0 then reverted back to 3.6.2.

Question:  Is there any way to export all the data from 3.6.2 then import it into a new installation of 3.7.0?

Unable to post with 3.7.0
[log_2017-10-30.txt](https://github.com/ryanhowdy/fcms/files/2488321/log_2017-10-30.txt)

Unable to upload photos with 3.6.2
[log_2018-10-08.txt](https://github.com/ryanhowdy/fcms/files/2488351/log_2018-10-08.txt)

**Comment by ryanhowdy** [comment]
The unable to post with 3.7.0 appears to be some login issue.  I would try again, but logout and then log back in and see if that helps.

The upload photos with 3.6.2 problem appears to be related to using php version 7.+.  Could you open up the inc/Database.php file and comment out line 103 and see if that solves your problem?

**Comment by GregLeonhardt** [comment]
With 3.7.0 the problem was 100% with multiple users, multiple login's and multiple reboots of the server and host OS.

For 3.6.2 I changed:

FROM:    103               array(PDO::ATTR_PERSISTENT => true)
TO:          103 //           array(PDO::ATTR_PERSISTENT => true)

I was unable to login because the login screen wouldn't display.  The only thing on what should have been the login screen was a # in the upper left corner.

**Comment by ryanhowdy** [comment]
The first part of this is a duplicate of #612 .

If the 2nd part is still an issue, lets open up a new issue for it.

**Comment by GregLeonhardt** [comment]
Yes, it's still an issue.  Do I open the issue? If so how is it done?
