### ISSUE TITLE
PHP Error  Function get_magic_quotes_gpc() is deprecated

### ISSUE THREAD

**Issue by ebretteville** [ryanhowdy/fcms#631]
Hye and thanks for the update, fresh install, I get the message (I can use the fcms and was able to finish the installation process):
`PHP Error

Function get_magic_quotes_gpc() is deprecated`

<img width="1002" alt="Capture d’écran 2022-08-21 à 11 10 15" src="https://user-images.githubusercontent.com/3687099/185784060-aa8808e7-83f1-4391-b2dd-9296cd6e483b.png">

**Comment by ryanhowdy** [comment]
You can fix this by commenting out lines 187 through 193 in familyconnections/fcms.php file.

```
/**
 * fixMagicQuotes 
 *
 * Strips slashes if magic quotes is turned on
 * 
 * @return void
 */
function fixMagicQuotes ()
{
    //if (get_magic_quotes_gpc())
    //{
    //    $_REQUEST = stripSlashesDeep($_REQUEST);
    //    $_GET     = stripSlashesDeep($_GET);
    //    $_POST    = stripSlashesDeep($_POST);
    //    $_COOKIE  = stripSlashesDeep($_COOKIE);
    //}
}
```

**Comment by ebretteville** [comment]
Thanks that did the trick
